#!/usr/bin/env python3
"""Generate / refresh ARCH.md — a deterministic, no-truncation file-tree map.

Design notes
------------
* File set comes from `git ls-files --cached --others --exclude-standard`, which
  respects `.gitignore` for BOTH blocklist and allowlist (`*` then `!path`) repos
  and is fully deterministic. (`tree --gitignore` silently empties allowlist repos.)
* Only the block between the ARCH:TREE markers is regenerated. The "## Overview"
  prose and the "## Key Paths" (ARCH:DESC) block are CURATED zones — preserved
  verbatim across runs. Populate them with the code-explorer agent.
* Inline one-line descriptions are sourced from the Key Paths block and injected
  next to matching tree entries on every regeneration, so they never go stale or
  get wiped.

Usage:
    gen_arch.py [--root DIR] [--quiet] [--check]

  --check : exit 1 if ARCH.md is out of date (CI guard); makes no changes.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

TREE_START = "<!-- ARCH:TREE:START — generated by gen_arch.py; do not edit inside, do not remove -->"
TREE_END = "<!-- ARCH:TREE:END -->"
DESC_START = "<!-- ARCH:DESC:START — curated; one line per key path, preserved across regens -->"
DESC_END = "<!-- ARCH:DESC:END -->"

# `- `path`` or `- `dir/`` followed by an em-dash / hyphen and a description.
DESC_LINE = re.compile(r"^- +`([^`]+)` +[—–-] +(.+?)\s*$")

# Volatile "Generated <when>" stamp — normalized away for idempotent comparison
# so the file only rewrites on real structural/description changes (not every run).
STAMP_RE = re.compile(r"_Generated \d{4}-\d\d-\d\d \d\d:\d\d UTC ")


def normalize(text: str) -> str:
    return STAMP_RE.sub("_Generated <STAMP> ", text)


def sh(args: list[str], cwd: Path) -> str:
    return subprocess.run(
        args, cwd=cwd, check=True, capture_output=True, text=True
    ).stdout


def list_paths(root: Path) -> list[str]:
    """Tracked + untracked-but-not-ignored files, .gitignore-respecting."""
    out = sh(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        root,
    )
    paths = [p for p in out.split("\0") if p]
    return sorted(set(paths))


# --------------------------------------------------------------------------- #
# Tree model
# --------------------------------------------------------------------------- #
class Node:
    __slots__ = ("name", "children", "is_dir")

    def __init__(self, name: str, is_dir: bool):
        self.name = name
        self.is_dir = is_dir
        self.children: dict[str, "Node"] = {}


def build_tree(paths: list[str]) -> Node:
    root = Node("", True)
    for p in paths:
        parts = p.split("/")
        cur = root
        for i, part in enumerate(parts):
            is_dir = i < len(parts) - 1
            child = cur.children.get(part)
            if child is None:
                child = Node(part, is_dir)
                cur.children[part] = child
            # a path component that later turns out to be a parent is a dir
            if is_dir:
                child.is_dir = True
            cur = child
    return root


def sorted_children(node: Node) -> list[Node]:
    # directories first, then files; each alphabetical (case-insensitive)
    return sorted(
        node.children.values(),
        key=lambda n: (not n.is_dir, n.name.lower()),
    )


def render(node: Node, descs: dict[str, str]) -> tuple[list[str], int, int]:
    """Return (lines, n_files, n_dirs). Root's own name is not printed."""
    lines: list[str] = []
    counts = {"files": 0, "dirs": 0}

    def walk(n: Node, prefix: str, path: str):
        kids = sorted_children(n)
        for i, child in enumerate(kids):
            last = i == len(kids) - 1
            connector = "└── " if last else "├── "
            child_path = f"{path}{child.name}"
            label = child.name + ("/" if child.is_dir else "")
            key = child_path + ("/" if child.is_dir else "")
            desc = descs.get(key) or descs.get(child_path)
            suffix = f"  — {desc}" if desc else ""
            lines.append(f"{prefix}{connector}{label}{suffix}")
            if child.is_dir:
                counts["dirs"] += 1
                ext = "    " if last else "│   "
                walk(child, prefix + ext, child_path + "/")
            else:
                counts["files"] += 1

    walk(node, "", "")
    return lines, counts["files"], counts["dirs"]


# --------------------------------------------------------------------------- #
# ARCH.md assembly (preserve curated zones)
# --------------------------------------------------------------------------- #
def parse_descs(text: str) -> dict[str, str]:
    descs: dict[str, str] = {}
    if DESC_START not in text:
        return descs
    block = text.split(DESC_START, 1)[1].split(DESC_END, 1)[0]
    for line in block.splitlines():
        m = DESC_LINE.match(line)
        if m:
            key, desc = m.group(1).strip(), m.group(2).strip()
            if desc and desc.upper() != "TODO":
                descs[key] = desc
    return descs


def default_scaffold(repo: str, top_level: list[Node]) -> str:
    seed = "\n".join(f"- `{n.name}{'/' if n.is_dir else ''}` — TODO" for n in top_level)
    return (
        f"# Architecture Map — {repo}\n\n"
        "> **Auto-maintained.** The file tree below (between the `ARCH:TREE` markers) is "
        "regenerated on every commit by `.githooks/pre-commit` and can be refreshed manually "
        "with `python3 .githooks/gen_arch.py`. The **Overview** and **Key Paths** sections are "
        "curated (fill them with the `code-explorer` agent); they are preserved across "
        "regenerations. Descriptions in *Key Paths* are injected inline into the tree.\n\n"
        "## Overview\n\n"
        "_Replace this with a short architectural overview (entry points, layers, data flow). "
        "Run the `code-explorer` agent to populate it._\n\n"
        "## Key Paths\n\n"
        f"{DESC_START}\n{seed}\n{DESC_END}\n\n"
        "## File Tree\n\n"
    )


def build_document(root: Path, existing: str | None) -> str:
    repo = root.name
    paths = list_paths(root)
    tree = build_tree(paths)
    descs = parse_descs(existing or "")
    lines, n_files, n_dirs = render(tree, descs)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    tree_block = (
        f"{TREE_START}\n```\n{repo}/\n"
        + ("\n".join(lines) + "\n" if lines else "")
        + "```\n"
        + f"\n_Generated {stamp} · {n_files} files · {n_dirs} directories._\n"
        + f"{TREE_END}\n"
    )

    if existing and TREE_START in existing and TREE_END in existing:
        prefix = existing.split(TREE_START, 1)[0]
        suffix = existing.split(TREE_END, 1)[1]
        doc = prefix + tree_block + suffix
    else:
        doc = default_scaffold(repo, sorted_children(tree)) + tree_block
    # exactly one trailing newline → idempotent (no blank-line growth across runs)
    return doc.rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate/refresh ARCH.md")
    ap.add_argument("--root", default=None, help="repo root (default: git toplevel)")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--check", action="store_true", help="exit 1 if stale; no write")
    args = ap.parse_args()

    if args.root:
        root = Path(args.root).resolve()
    else:
        try:
            root = Path(
                sh(["git", "rev-parse", "--show-toplevel"], Path.cwd()).strip()
            )
        except subprocess.CalledProcessError:
            print("gen_arch: not inside a git repository", file=sys.stderr)
            return 2

    arch = root / "ARCH.md"
    existing = arch.read_text(encoding="utf-8") if arch.exists() else None
    new_doc = build_document(root, existing)

    changed = existing is None or normalize(existing) != normalize(new_doc)

    if args.check:
        if changed:
            print(f"gen_arch: {arch} is OUT OF DATE — run gen_arch.py", file=sys.stderr)
            return 1
        if not args.quiet:
            print(f"gen_arch: {arch} up to date")
        return 0

    if not changed:
        if not args.quiet:
            print(f"gen_arch: {arch} unchanged")
        return 0

    tmp = arch.with_suffix(".md.tmp")
    tmp.write_text(new_doc, encoding="utf-8")
    tmp.replace(arch)
    if not args.quiet:
        print(f"gen_arch: wrote {arch}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
